### ISSUE TITLE
Decide what colors of lights should mean.

### ISSUE THREAD

**Issue by mmilunicmobile** [FRC2539/javabot-2024#5]
This includes:
* Sees target
* Sees piece
* Ready to shoot
* Shooting
* Anything else you can think of...

**Comment by mmilunicmobile** [comment]
You can leave your feedback here!!!!!

**Comment by mmilunicmobile** [comment]
I personally think that if it detects a piece in the intake it should show a bright white. If it sees a shooter target, it should show a blue, and if it is ready to shoot it should show a green. If it sees a piece i think it should show/flash a purple (as orange is taken). If we need a trap piece it could flash yellow.

**Comment by We-Gold** [comment]
Last year we had flash yellow for not aimed and green for aimed. I think blue and green are pretty visually similar, so yellow might make it easier to distinguish.

**Comment by mmilunicmobile** [comment]
> Default to orange.
> Sensor sees game piece is white flash.
> Flashing yellow for not lined up when shooting/amping/trapping/source lineup
> Solid green for lined up when shooting/amping/trapping/source lineup
> Solid blue for sees piece when ML intaking
> Flashing red for when it does not see piece while ML intaking
> Flashing purple for slide intake signaling.
> Rainbow for climbed
- Quinn & Matthew

**Comment by mmilunicmobile** [comment]
These seem good.
